from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.ui import Select
from selenium import webdriver
from selenium.webdriver.chrome.service import Service as ChromeService
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver import Keys
from time import sleep
from faker import Faker
from time import sleep

fake =Faker()

driver = webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()))

driver.get("https://opendoors--qa.sandbox.my.salesforce.com")
driver.maximize_window()

wait = WebDriverWait(driver, 15)
# Login Page
driver.find_element(By.CSS_SELECTOR, "#logo")
driver.find_element(By.CSS_SELECTOR, "#username").send_keys("udeme@opendoorsatl.org.qa")
driver.find_element(By.CSS_SELECTOR, "#password").send_keys("1Gconnect.")
driver.find_element(By.CSS_SELECTOR, "#Login").click()
# Home Page
driver.find_element(By.CSS_SELECTOR, "div[class='slds-global-header__item'] div[class='slds-global-header__logo']")
title = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[1]/section/div[1]/div[1]/one-appnav/div/div/div/h1/span")))
print("Page title:", title.text)
# SF Tabs
driver.find_element(By.XPATH, "//span[@class='slds-truncate'][normalize-space()='Home']")
sleep(20)
driver.find_element(By.XPATH, "//span[@class='slds-truncate'][normalize-space()='Accounts']")
driver.find_element(By.XPATH, "//span[@class='slds-truncate'][normalize-space()='Contacts']")
driver.find_element(By.XPATH, "//span[@class='slds-truncate'][normalize-space()='Properties']")
driver.find_element(By.XPATH, "//span[@class='slds-truncate'][normalize-space()='Referrals']")
driver.find_element(By.XPATH, "//span[@class='slds-truncate'][normalize-space()='Reports']")
driver.find_element(By.XPATH, "//span[@class='slds-truncate'][normalize-space()='Dashboards']")
driver.find_element(By.XPATH, "//a[@class='slds-button slds-button_reset slds-context-bar__label-action']")
driver.find_element(By.XPATH, "//span[@class='slds-truncate'][normalize-space()='People']")
driver.find_element(By.XPATH, "//span[@class='slds-truncate'][normalize-space()='Unit Availability']")
driver.find_elements(By.XPATH, "//span[@class='slds-truncate'][normalize-space()='Applicants']")
driver.find_element(By.XPATH, "//span[@class='slds-p-right_small']")
driver.find_element(By.XPATH, "//lightning-icon[@class='slds-icon-utility-down slds-icon_container']//lightning-primitive-icon[@exportparts='icon']//*[name()='svg']").click()
driver.find_element(By.XPATH, "//span[@class='slds-truncate']//span[contains(text(),'Rental Concessions')]")
driver.find_element(By.XPATH, "//span[@class='slds-truncate']//span[contains(text(),'DocuSign Envelope Recipients')]")
driver.find_element(By.XPATH, "//span[@class='slds-truncate']//span[contains(text(),'Property Inspection')]")
# Home Page Dashboard
wait.until(ec.element_to_be_clickable((By.CSS_SELECTOR, "span[title='Today’s Tasks']")))
wait.until(ec.element_to_be_clickable((By.CSS_SELECTOR, "span[title=\"Today's Events\"]")))

#Properties Tab
wait.until(ec.element_to_be_clickable((By.CSS_SELECTOR, 'a[href="/lightning/o/Property__c/home"]')))
driver.find_element(By.CSS_SELECTOR, 'a[href="/lightning/o/Property__c/home"]').click()
# pageTitle = wait.until(ec.element_to_be_clickable((By.LINK_TEXT, "Properties")))
# print("Title on page is: ", pageTitle.text)
# assert pageTitle.text == "Properties"
# New Property
#wait.until(ec.element_to_be_clickable((By.CSS_SELECTOR, "li:nth-of-type(1) > a[role='button']")))
#driver.find_element(By.CSS_SELECTOR, "li:nth-of-type(1) > a[role='button']").click()
driver.find_element(By.CSS_SELECTOR, "body > div.desktop.container.forceStyle.oneOne.navexDesktopLayoutContainer.lafAppLayoutHost.forceAccess > div.viewport > section > div.full.navexStandardManager > div.slds-no-print.oneAppNavContainer > one-appnav > div > one-app-nav-bar > nav > div > one-app-nav-bar-item-root.navItem.slds-context-bar__item.slds-shrink-none.slds-is-active > one-app-nav-bar-item-dropdown > div > one-app-nav-bar-menu-button > a > lightning-icon > span > lightning-primitive-icon > svg").click()
wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//h2[.='New Property']")))
pageTitle = driver.find_element(By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//h2[.='New Property']")
print("Title on page is: ", pageTitle.text)
assert pageTitle.text == "New Property"
## Property Information
### Generate a unique product name
product_name = fake.word().capitalize() + " " + fake.word().capitalize()
### Locate the product name input field and send the generated product name
product_input = wait.until(ec.element_to_be_clickable((By.XPATH, "/html[1]/body[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/one-record-action-flexipage[1]/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[1]/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[1]/record_flexipage-desktop-record-page-decorator[1]/div[1]/records-record-layout-event-broker[1]/slot[1]/slot[1]/flexipage-record-home-single-col-no-header-template-desktop2[1]/div[1]/div[1]/div[1]/slot[1]/flexipage-component2[1]/slot[1]/flexipage-field-section2[1]/div[1]/div[1]/div[1]/laf-progressive-container[1]/slot[1]/dl[1]/slot[1]/flexipage-column2[1]/div[1]/slot[1]/flexipage-field[1]/slot[1]/record_flexipage-record-field[1]/div[1]/div[2]/slot[1]/records-record-layout-base-input[1]/lightning-input[1]/lightning-primitive-input-simple[1]/div[1]/div[1]/input[1]")))
product_input.send_keys(product_name)
# Submit the form
product_input.send_keys(Keys.RETURN)
### Select a status
statusDropdown = driver.find_element(By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[1]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[2]//slot[@class='column']/flexipage-field[2]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox//lightning-base-combobox[@class='slds-combobox_container']//div[@role='none']/button[@role='combobox']")
statusDropdown.click()
none = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[1]/span[2]/span")))
none.click()
statusDropdown.click()
inactive = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[2]/span[2]/span")))
inactive.click()
statusDropdown.click()
live = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[4]/span[2]/span")))
live.click()
statusDropdown.click()
active_notListed = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[5]/span[2]/span")))
active_notListed.click()
statusDropdown.click()
engaging_transition = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[6]/span[2]/span")))
engaging_transition.click()
statusDropdown.click()
active_lead = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[7]/span[2]/span")))
active_lead.click()
statusDropdown.click()
lost_lead = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[8]/span[2]/span")))
lost_lead.click()
statusDropdown.click()
driver.execute_script("window.scrollBy(0, 1000);")
lift_campign = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[9]/span[2]/span")))
#lift_campign.click()
#statusDropdown.click()
#rentBridge = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[10]/span[2]/span")))
#rentBridge.click()
#statusDropdown.click()
pending = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[3]/span[2]/span")))
pending.click()
rent_income = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[1]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[1]//slot[@class='column']/flexipage-field[5]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-layout-base-input/lightning-input[@class='slds-form-element slds-form-element_stacked']/lightning-primitive-input-simple//div[@class='slds-form-element__control slds-grow']/input[@name='Rent_to_Income_Ratio__c']")))
rent_income.send_keys("5")
leased = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[1]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[2]//slot[@class='column']/flexipage-field[4]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/lightning-input[@class='slds-form-element slds-form-element_stacked']/lightning-primitive-input-simple//div[@class='slds-form-element__control slds-grow']/input[@name='Occupancy__c']")))
leased.send_keys("1.5")
contact_frequency = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[1]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[1]//slot[@class='column']/flexipage-field[7]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-layout-base-input/lightning-input[@class='slds-form-element slds-form-element_stacked']/lightning-primitive-input-simple//div[@class='slds-form-element__control slds-grow']/input[@name='Contact_Frequency__c']")))
contact_frequency.send_keys("Twice")
renters_insurance = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[1]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[2]//slot[@class='column']/flexipage-field[11]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox//lightning-base-combobox[@class='slds-combobox_container']//div[@role='none']/button[@role='combobox']/span[@class='slds-truncate']")))
renters_insurance.click()
dropdown_list = driver.find_element(By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[11]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]")
not_required = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[11]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-picklist/records-form-picklist/lightning-picklist/lightning-combobox/div/div[1]/lightning-base-combobox/div/div/div[2]/lightning-base-combobox-item[2]")))
not_required.click()
minimum_credit_score = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[1]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[2]//slot[@class='column']/flexipage-field[13]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/lightning-input[@class='slds-form-element slds-form-element_stacked']/lightning-primitive-input-simple//div[@class='slds-form-element__control slds-grow']/input[@name='Minimum_credit_score__c']")))
minimum_credit_score.send_keys("500")
description = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']/div[4]/div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[3]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[@class='column flex-width']//slot[@class='column']/flexipage-field[1]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-layout-text-area/lightning-textarea[@class='slds-form-element slds-form-element_stacked']//textarea[@class='slds-textarea']")))
description.send_keys("A test property created during an automation run")
###multiunit_campaign_options 
lift= wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[3]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[@class='column flex-width']//slot[@class='column']/flexipage-field[2]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-picklist/records-form-picklist/lightning-picklist/lightning-dual-listbox/div[@role='group']//div[@class='slds-dueling-list']/div[3]/div[@class='slds-dueling-list__options']/ul[@role='listbox']/li[1]/div[@role='option']//span[@title='Lift 2.0']")))
assert lift.text == "Lift 2.0"
lift.click()
print("The first multiunit campaign selected is: ", lift.text)
next = driver.find_element(By.XPATH, "//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[3]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[@class='column flex-width']//slot[@class='column']/flexipage-field[2]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-picklist/records-form-picklist/lightning-picklist/lightning-dual-listbox/div[@role='group']//div[@class='slds-dueling-list__column']/lightning-button-icon[1]/button[@title='Move to Chosen']/lightning-primitive-icon")
next.click()
sleep(3)
### Address and contact Information
phone_number = fake.phone_number()
phone = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[4]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[2]//slot[@class='column']/flexipage-field[1]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/lightning-input[@class='slds-form-element slds-form-element_stacked']/lightning-primitive-input-simple//div[@class='slds-form-element__control slds-grow']/input[@name='Phone__c']")))
phone.send_keys(phone_number)
email_address = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[4]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[2]//slot[@class='column']/flexipage-field[2]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/lightning-input[@class='slds-form-element slds-form-element_stacked']/lightning-primitive-input-simple//div[@class='slds-form-element__control slds-grow']/input[@name='Email__c']")))
email_address.send_keys("up@yopmail.com")
street = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[4]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[1]//slot[@class='column']/flexipage-field[2]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-layout-base-input/lightning-input[@class='slds-form-element slds-form-element_stacked']/lightning-primitive-input-simple//div[@class='slds-form-element__control slds-grow']/input[@name='Address_Street__c']")))
street.send_keys("5678 north road")
city_address = wait.until(ec.visibility_of_element_located((By.CSS_SELECTOR, ".slds-form-element__control.slds-grow > input[name='Address_City__c']")))
city_address.send_keys("Atlanta")
state = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[4]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[1]//slot[@class='column']/flexipage-field[4]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-layout-base-input/lightning-input[@class='slds-form-element slds-form-element_stacked']/lightning-primitive-input-simple//div[@class='slds-form-element__control slds-grow']/input[@name='State__c']")))
state.send_keys("GA")
zip = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[4]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[1]//slot[@class='column']/flexipage-field[5]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-layout-base-input/lightning-input[@class='slds-form-element slds-form-element_stacked']/lightning-primitive-input-simple//div[@class='slds-form-element__control slds-grow']/input[@name='Zip__c']")))
zip.send_keys("330301")
county = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']//div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[4]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[1]//slot[@class='column']/flexipage-field[6]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-layout-base-input/lightning-input[@class='slds-form-element slds-form-element_stacked']/lightning-primitive-input-simple//div[@class='slds-form-element__control slds-grow']/input[@name='County__c']")))
county.send_keys("Decatur")
### Management Information
mgt_acct = wait.until(ec.visibility_of_element_located((By.XPATH, "//body[@class='desktop']/div[4]/div[@class='DESKTOP uiContainerManager']/div/div[@role='dialog']//div[@class='modal-body scrollable slds-modal__content slds-p-around_medium']//one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___create___-l-m-t___1738608849000[@class='adg-rollup-wrapped']/forcegenerated-flexipage_property_details_with_header_property__c__create_js___lmt___1738608849000[@class='forcegenerated-flexipage-module']/record_flexipage-desktop-record-page-decorator//records-record-layout-event-broker//flexipage-record-home-single-col-no-header-template-desktop2[@class='forcegenerated-flexipage-template']//slot[@name='main']/flexipage-component2[5]//flexipage-field-section2//laf-progressive-container//dl/slot[@name='columns']/flexipage-column2[1]//slot[@class='column']/flexipage-field[1]//record_flexipage-record-field[@role='listitem']//slot[@name='input']/records-record-layout-lookup/lightning-lookup/lightning-lookup-desktop/lightning-grouped-combobox[@class='slds-form-element']//lightning-base-combobox[@class='slds-combobox_container']//div[@role='none']//input[@role='combobox']")))
mgt_acct.click()
Manage_acct = wait.until(ec.visibility_of_element_located (By.CSS_SELECTOR, "#combobox-input-2792"))
Manage_acct.send_keys("Unique Udeme")
owner_acct = wait.until(ec.visibility_of_element_located (By.CSS_SELECTOR, "#combobox-input-5200"))
owner_acct.send_keys("Agent Unique")
onsite_mgt = wait.until(ec.visibility_of_element_located (By.CSS_SELECTOR, "#combobox-input-5209"))
onsite_mgt.send_keys("Unique Agent")
save1 = wait.until(ec.visibility_of_element_located (By.XPATH, '/html/body/div[4]/div[2]/div[6]/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-property_-details_with_-header___-property__c___edit___-l-m-t___1739977362000/forcegenerated-flexipage_property_details_with_header_property__c__edit_js___lmt___1739977362000/record_flexipage-desktop-record-page-decorator/div[1]/records-form-footer/div/div/div/runtime_platform_actions-actions-ribbon/ul/li[3]/runtime_platform_actions-action-renderer/runtime_platform_actions-executor-lwc-headless/slot[1]/slot/lightning-button/button'))
save1.click()

###New Property inspection(HQS)
inspection_new = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[1]/section/div[1]/div[2]/div[1]/div/div/div/div/div/div/div/lst-object-home/div/lst-list-view-manager/lst-common-list-internal/lst-list-view-manager-header/div/div[1]/div[3]/div/ul/li[1]/a")))
inspection_new.click()
unit_name = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div[4]/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-unit_-availability_-record_-page___-unit_-availability__c___create___-l-m-t___1734038354000/forcegenerated-flexipage_unit_availability_record_page_unit_availability__c__create_js___lmt___1734038354000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[1]/div/slot/flexipage-field[1]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-layout-base-input/lightning-input/lightning-primitive-input-simple/div[1]/div/input")))
unit_name.send_keys("love")
newproperty = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div[4]/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-unit_-availability_-record_-page___-unit_-availability__c___create___-l-m-t___1734038354000/forcegenerated-flexipage_unit_availability_record_page_unit_availability__c__create_js___lmt___1734038354000/record_flexipage-desktop-record-page-decorator/div[1]/records-record-layout-event-broker/slot/slot/flexipage-record-home-single-col-no-header-template-desktop2/div/div/div/slot/flexipage-component2[1]/slot/flexipage-field-section2/div/div/div/laf-progressive-container/slot/dl/slot/flexipage-column2[2]/div/slot/flexipage-field[2]/slot/record_flexipage-record-field/div/div[2]/slot/records-record-layout-lookup/lightning-lookup/lightning-lookup-desktop/lightning-grouped-combobox/div[1]/div/lightning-base-combobox/div/div/div[1]/div[1]/div/input")))
newproperty.click()
#cannot pick property from dropdown
save2 = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div[4]/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-unit_-availability_-record_-page___-unit_-availability__c___create___-l-m-t___1734038354000/forcegenerated-flexipage_unit_availability_record_page_unit_availability__c__create_js___lmt___1734038354000/record_flexipage-desktop-record-page-decorator/div[1]/records-form-footer/div/div/div/runtime_platform_actions-actions-ribbon/ul/li[3]/runtime_platform_actions-action-renderer/runtime_platform_actions-executor-lwc-headless/slot[1]/slot/lightning-button/button")))
save2.click()
unit_inspection = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div[4]/div[2]/div/div[2]/div/div/div/one-record-action-flexipage/forcegenerated-adg-rollup_component___force-generated__flexipage_-record-page___-unit_-availability_-record_-page___-unit_-availability__c___create___-l-m-t___1734038354000/forcegenerated-flexipage_unit_availability_record_page_unit_availability__c__create_js___lmt___1734038354000/record_flexipage-desktop-record-page-decorator/div[1]/records-form-footer/div/div/div/runtime_platform_actions-actions-ribbon/ul/li[3]/runtime_platform_actions-action-renderer/runtime_platform_actions-executor-lwc-headless/slot[1]/slot/lightning-button/button")))
unit_inspection.click()
status_inspection = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div[4]/div[2]/div/div[2]/div/div/div[2]/div/article/flowruntime-flow/flowruntime-lwc-body/div/flowruntime-list-container/div/flowruntime-base-section/div/flowruntime-screen-field[8]/flowruntime-lwc-field/div/flowruntime-picklist-input-lwc/div/lightning-select/div/div/select")))
status_inspection.click()
#cannot pick status from dropdown
upload= wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div[4]/div[2]/div/div[2]/div/div/div[2]/div/article/flowruntime-flow/flowruntime-lwc-body/div/flowruntime-list-container/div/flowruntime-base-section/div/flowruntime-screen-field[13]/flowruntime-lwc-field/div/c-file-upload-improved/lightning-layout/slot/lightning-layout-item[1]/slot/lightning-file-upload/lightning-input/lightning-primitive-input-file/div[1]/div/lightning-primitive-file-droppable-zone/slot/label/span[1]")))
upload.click()
Done1= wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div[5]/div[2]/div/div[3]/div/span[2]/button/span")))
Done1.click()
Submit1= wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div[4]/div[2]/div/div[2]/div/div/div[2]/div/article/flowruntime-flow/flowruntime-navigation-bar/footer/div/lightning-button/button")))
Submit1.click()
complete1= wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[2]/div[4]/div[2]/div/div[2]/div/div/div[2]/div/article/flowruntime-flow/flowruntime-navigation-bar/footer/div/lightning-button/button")))
complete1.click()

###New Property inspection(Soft walk)
properties2 = driver.find_element(By.XPATH, "/html/body/div[4]/div[1]/section/div[1]/div[1]/one-appnav/div/one-app-nav-bar/nav/div/one-app-nav-bar-item-root[4]/a")
properties2.click()
property_new = wait.until(ec.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[1]/section/div[1]/div[2]/div[1]/div/div/div/div/div/div/div/lst-object-home/div/lst-list-view-manager/lst-common-list-internal/div/div/lst-primary-display-manager/div/lst-primary-display/lst-primary-display-grid/lightning-datatable/div[2]/div/div/table/tbody/tr[1]/th/span/div/lightning-primitive-custom-cell/lst-output-lookup/force-lookup/div/a/slot/span")))
property_new.click()


driver.quit()